"""
Topic 정의 및 DB 시드 데이터

TOPIC_SEED: 서버 최초 실행 시 topic 테이블에 삽입되는 초기 데이터
  - is_system=True 항목은 삭제 불가 (campus, graduation, scholarship, general)
  - handler_type: 라우팅할 핸들러 코드 지정
      "campus"      → _handle_campus
      "graduation"  → _handle_graduation
      "scholarship" → _handle_scholarship
      "rag"         → _handle_rag_general
      "general"     → _handle_general
"""

TOPIC_SEED: list[dict] = [
    # ── 시스템 topic (삭제 불가) ────────────────────────────
    {
        "name": "campus",
        "label": "캠퍼스/시설",
        "handler_type": "campus",
        "is_system": True,
        "description": "건물 위치, 캠퍼스 시설 안내",
        "sentences": [
            "도서관이 어디에 있나요?",
            "동아리 건물 위치가 어디예요?",
            "학과 사무실은 몇 층에 있나요?",
            "강의실을 찾고 싶어요",
            "식당은 어디에 있어요?",
            "체육관 위치가 어디인가요?",
            "캠퍼스 지도를 알고 싶어요",
            "호실이 어디에 있나요?",
            "몇 층에 있나요?",
            "W1 건물이 어디 있나요?",
            "W3 강의실은 어떻게 가나요?",
            "W7 위치가 어디인가요?",
            "W15 어디예요?",
            "E3 건물 위치 알려주세요",
            "S2 건물이 어디예요?",
            "우송도서관이 어디에 있나요?",
            "학술정보관 위치가 어디예요?",
            "대학본부는 어디에 있나요?",
            "학생회관은 어디에 있나요?",
            "우송관 위치가 어디예요?",
            "교양교육관은 어디에 있어요?",
            "산학협력관이 어디에 있나요?",
            "철도물류관 위치 알려주세요",
            "보건의료과학관이 어디에 있나요?",
            "사회복지융합관이 어디에 있나요?",
            "미디어융합관 위치 알려주세요",
            "우송예술회관이 어디에 있나요?",
            "테크노디자인센터 어디에 있어요?",
            "국제경영센터 위치가 어디예요?",
            "엔디콧 건물이 어디에 있나요?",
            "컬리너리 센터는 어디에 있나요?",
            "식품건축관이 어디에 있나요?",
            "어학센터 위치 알려주세요",
            "IT교육센터가 어디에 있나요?",
            "뷰티센터 어디에 있어요?",
            "스포츠센터 위치가 어디예요?",
            "기숙사 위치가 어디예요?",
            "유학생기숙사가 어디에 있나요?",
            "우송타워는 어디에 있나요?",
        ],
    },
    {
        "name": "graduation",
        "label": "졸업요건",
        "handler_type": "graduation",
        "is_system": True,
        "description": "졸업 요건 확인, 이수 학점 조회",
        "sentences": [
            "졸업하려면 학점이 몇 점 필요한가요?",
            "졸업요건이 어떻게 되나요?",
            "전공필수 과목을 다 들어야 졸업할 수 있나요?",
            "교양필수 이수 학점은 몇 학점인가요?",
            "졸업까지 부족한 학점이 얼마나 되나요?",
            "졸업 가능 여부를 확인하고 싶어요",
            "이수조건을 알고 싶어요",
        ],
    },
    {
        "name": "scholarship",
        "label": "장학금",
        "handler_type": "scholarship",
        "is_system": True,
        "description": "장학금 신청, 종류, 자격 조건 안내",
        "sentences": [
            "장학금 신청 방법을 알고 싶어요",
            "장학금을 받으려면 어떻게 해야 하나요?",
            "국가장학금 신청은 어떻게 하나요?",
            "성적 장학금은 어떻게 받을 수 있나요?",
            "장학금 종류가 어떻게 되나요?",
            "장학금 신청 기간이 언제인가요?",
            "어떤 장학금이 있나요?",
            "장학금 받을 수 있을까요?",
        ],
    },
    {
        "name": "general",
        "label": "일반 대화",
        "handler_type": "general",
        "is_system": True,
        "description": "학교와 무관한 일반 질문",
        "sentences": [],
    },
    # ── RAG topic (추가/삭제 가능) ──────────────────────────
    {
        "name": "schedule",
        "label": "학사일정",
        "handler_type": "rag",
        "is_system": False,
        "description": "개강일, 방학, 학사 일정 안내",
        "sentences": [
            "학사일정을 알려주세요",
            "이번 학기 일정이 어떻게 되나요?",
            "개강일이 언제인가요?",
            "방학 일정이 어떻게 되나요?",
            "시험 기간이 언제인가요?",
            "학사 공지사항이 있나요?",
        ],
    },
    {
        "name": "leave",
        "label": "휴학/복학",
        "handler_type": "rag",
        "is_system": False,
        "description": "휴학, 복학 신청 절차",
        "sentences": [
            "휴학 신청은 어떻게 하나요?",
            "복학하려면 어떻게 해야 하나요?",
            "휴학 기간이 얼마나 되나요?",
            "군 휴학 신청 방법이 어떻게 되나요?",
            "복학 신청 절차가 어떻게 되나요?",
            "휴학 중에 등록금을 내야 하나요?",
        ],
    },
    {
        "name": "dormitory",
        "label": "기숙사",
        "handler_type": "rag",
        "is_system": False,
        "description": "기숙사 신청, 생활 안내",
        "sentences": [
            "기숙사 신청 방법이 어떻게 되나요?",
            "생활관 입사 절차가 어떻게 되나요?",
            "기숙사 비용이 얼마인가요?",
            "기숙사 규정이 어떻게 되나요?",
            "기숙사 신청 자격이 어떻게 되나요?",
            "기숙사 생활 관련 문의가 있어요",
        ],
    },
    {
        "name": "course_registration",
        "label": "수강신청",
        "handler_type": "rag",
        "is_system": False,
        "description": "수강신청 방법, 기간 안내",
        "sentences": [
            "수강신청은 언제 하나요?",
            "수강신청 방법이 어떻게 되나요?",
            "수강신청 기간은 언제인가요?",
            "수강 취소는 어떻게 하나요?",
            "전공 과목 수강신청 방법을 알고 싶어요",
            "수강 정정 기간이 언제인가요?",
        ],
    },
    {
        "name": "special_credit",
        "label": "특별학점",
        "handler_type": "rag",
        "is_system": False,
        "description": "자격증, 봉사활동 등 특별학점 인정",
        "sentences": [
            "특별학점 신청 방법은요?",
            "봉사활동으로 학점을 받을 수 있나요?",
            "자격증으로 학점 인정이 되나요?",
            "어학성적으로 학점 취득이 가능한가요?",
            "특별학점 인정 기준이 어떻게 되나요?",
        ],
    },
    {
        "name": "grades",
        "label": "성적",
        "handler_type": "rag",
        "is_system": False,
        "description": "성적 이의신청, GPA 계산",
        "sentences": [
            "성적 이의신청은 어떻게 하나요?",
            "학점 계산 방법이 어떻게 되나요?",
            "GPA 계산은 어떻게 하나요?",
            "성적 확인은 어디서 하나요?",
            "성적 이의신청 기간이 언제인가요?",
        ],
    },
    {
        "name": "school_rules",
        "label": "학칙/규정",
        "handler_type": "rag",
        "is_system": False,
        "description": "학칙, 학생 생활 규정",
        "sentences": [
            "학칙이 어떻게 되나요?",
            "학교 규정에 대해 알고 싶어요",
            "학생 규칙에는 어떤 게 있나요?",
            "학교 규정 위반 시 처벌은 어떻게 되나요?",
            "학칙 내용을 알고 싶어요",
        ],
    },
    {
        "name": "absence",
        "label": "공결",
        "handler_type": "rag",
        "is_system": False,
        "description": "공결, 출석인정 신청",
        "sentences": [
            "공결 처리는 어떻게 하나요?",
            "출석인정 신청 방법이 어떻게 되나요?",
            "결석 사유서는 어디에 내나요?",
            "공결 신청 기간이 어떻게 되나요?",
            "병결 처리 방법이 어떻게 되나요?",
        ],
    },
    {
        "name": "multi_major",
        "label": "복수/부전공",
        "handler_type": "rag",
        "is_system": False,
        "description": "복수전공, 부전공 신청 안내",
        "sentences": [
            "복수전공 신청 방법이 어떻게 되나요?",
            "부전공을 하고 싶어요",
            "복수전공 이수 학점이 얼마나 되나요?",
            "복수전공 신청 시기가 언제인가요?",
            "부전공 요건이 어떻게 되나요?",
        ],
    },
    {
        "name": "academic_status",
        "label": "학적변동",
        "handler_type": "rag",
        "is_system": False,
        "description": "전과, 자퇴, 재입학 안내",
        "sentences": [
            "전과 신청은 어떻게 하나요?",
            "자퇴 절차가 어떻게 되나요?",
            "재입학 신청 방법이 어떻게 되나요?",
            "학적 변동 사항을 알고 싶어요",
            "전과 가능 시기가 언제인가요?",
        ],
    },
    {
        "name": "student_support",
        "label": "학생지원",
        "handler_type": "rag",
        "is_system": False,
        "description": "동아리, 오리엔테이션, 학생지원 프로그램",
        "sentences": [
            "동아리 가입하려면 어떻게 해야 하나요?",
            "어떤 동아리가 있나요?",
            "동아리 종류 알려주세요",
            "오리엔테이션 일정이 어떻게 되나요?",
            "OT는 언제 하나요?",
            "학생지원 프로그램 신청하고 싶어요",
            "학생카드 신청 방법이 어떻게 되나요?",
        ],
    },
    {
        "name": "rotc",
        "label": "ROTC/학군단",
        "handler_type": "rag",
        "is_system": False,
        "description": "ROTC, 학군단 지원 안내",
        "sentences": [
            "ROTC 지원 방법이 어떻게 되나요?",
            "학군단에 어떻게 지원하나요?",
            "ROTC 선발 기준이 어떻게 되나요?",
            "사관후보생이 되려면 어떻게 해야 하나요?",
            "군사학 수업은 어떻게 운영되나요?",
        ],
    },
    {
        "name": "rag_general",
        "label": "일반 학사",
        "handler_type": "rag",
        "is_system": False,
        "description": "기타 학사 관련 일반 질문",
        "sentences": [
            "학교 관련 정보를 알고 싶어요",
            "증명서 발급은 어디서 하나요?",
            "학교생활 안내가 필요해요",
            "학교에서 지원받을 수 있는 게 뭐가 있나요?",
        ],
    },
]

# 하위 호환 — admin_service 등에서 VALID_TOPICS를 참조할 경우 사용
# 런타임에는 DB에서 로드한 값을 사용해야 함
TOPICS: dict[str, str] = {t["name"]: t["label"] for t in TOPIC_SEED}
VALID_TOPICS: set[str] = set(TOPICS.keys())
